repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.35.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        files: src/python
  - repo: https://github.com/prettier/pre-commit
    rev: 57f39166b5a5a504d6808b87ab98d41ebf095b46
    hooks:
      - id: prettier
        files: src/typescript/
